In [1]:
import pandas as pd

In [2]:
crime_data = pd.read_excel('2019_Crime_Rates.xlsx')

In [3]:
crime_data.head()

,State,Population,Violent Crime,Murder and Non Negligent Man Slaughter,Rape,Robbery,Aggrevated Assault,Property \ncrime,Burglary,Larceny-theft,Motor \nvehicle \ntheft
0,ALABAMA,4903185,25046,358,2068,3941,18679,131133,26079,92477,12577
1,ALASKA,731545,6343,69,1088,826,4360,21294,3563,15114,2617
2,ARIZONA,7278717,33141,365,3662,6410,22704,177638,28699,130788,18151
3,ARKANSAS,3017804,17643,242,2331,1557,13513,86250,18095,60735,7420
4,CALIFORNIA,39512223,174331,1690,14799,52301,105541,921114,152555,626802,141757

In [4]:
crime_data.columns

Index(['State', 'Population', 'Violent Crime',
       'Murder and Non Negligent Man Slaughter', 'Rape', 'Robbery',
       'Aggrevated Assault', 'Property \ncrime', 'Burglary', 'Larceny-theft',
       'Motor \nvehicle \ntheft'],
      dtype='object')

In [5]:
crime_columns = ['Violent Crime','Murder and Non Negligent Man Slaughter', 'Rape', 'Robbery', 'Aggrevated Assault', 
                 'Property \ncrime', 'Burglary', 'Larceny-theft', 'Motor \nvehicle \ntheft']

In [6]:
for column in crime_columns:
    new_column_name = column + '_per_100k'
    crime_data[new_column_name] = ((crime_data[column] / crime_data['Population']) * 100000).round().astype(int)

In [7]:
crime_data.head()

,State,Population,Violent Crime,Murder and Non Negligent Man Slaughter,Rape,Robbery,Aggrevated Assault,Property \ncrime,Burglary,Larceny-theft,Motor \nvehicle \ntheft,Violent Crime_per_100k,Murder and Non Negligent Man Slaughter_per_100k,Rape_per_100k,Robbery_per_100k,Aggrevated Assault_per_100k,Property \ncrime_per_100k,Burglary_per_100k,Larceny-theft_per_100k,Motor \nvehicle \ntheft_per_100k
0,ALABAMA,4903185,25046,358,2068,3941,18679,131133,26079,92477,12577,511,7,42,80,381,2674,532,1886,257
1,ALASKA,731545,6343,69,1088,826,4360,21294,3563,15114,2617,867,9,149,113,596,2911,487,2066,358
2,ARIZONA,7278717,33141,365,3662,6410,22704,177638,28699,130788,18151,455,5,50,88,312,2441,394,1797,249
3,ARKANSAS,3017804,17643,242,2331,1557,13513,86250,18095,60735,7420,585,8,77,52,448,2858,600,2013,246
4,CALIFORNIA,39512223,174331,1690,14799,52301,105541,921114,152555,626802,141757,441,4,37,132,267,2331,386,1586,359

In [8]:
output_file_path = '2019_Crime_rates_per100k.xlsx'
crime_data.to_excel(output_file_path, index=False)

In [9]:
crime_data.columns

Index(['State', 'Population', 'Violent Crime',
       'Murder and Non Negligent Man Slaughter', 'Rape', 'Robbery',
       'Aggrevated Assault', 'Property \ncrime', 'Burglary', 'Larceny-theft',
       'Motor \nvehicle \ntheft', 'Violent Crime_per_100k',
       'Murder and Non Negligent Man Slaughter_per_100k', 'Rape_per_100k',
       'Robbery_per_100k', 'Aggrevated Assault_per_100k',
       'Property \ncrime_per_100k', 'Burglary_per_100k',
       'Larceny-theft_per_100k', 'Motor \nvehicle \ntheft_per_100k'],
      dtype='object')